import { Spell } from '../types';

export async function loadSpellsFromCSV(fileUrl: string): Promise<Spell[]> {
  try {
    const response = await fetch(fileUrl);
    if (!response.ok) {
      throw new Error(`Failed to fetch CSV: ${response.statusText}`);
    }
    
    const csvText = await response.text();
    const spells = parseCSV(csvText);
    return spells;
  } catch (error) {
    console.error('Error loading spells:', error);
    return [];
  }
}

function parseCSV(csvText: string): Spell[] {
  const lines = csvText.split('\n');
  const headers = lines[0].split(',').map(header => header.trim());
  
  const spells: Spell[] = [];
  
  for (let i = 1; i < lines.length; i++) {
    if (!lines[i].trim()) continue;
    
    const values = parseCSVLine(lines[i]);
    if (values.length !== headers.length) {
      console.warn(`Skipping line ${i}: column count mismatch`);
      continue;
    }
    
    const spell: Record<string, any> = {};
    
    headers.forEach((header, index) => {
      const value = values[index].trim();
      
      if (header === 'Level') {
        spell[header] = parseInt(value, 10);
      } else if (['Verbal', 'Somatic', 'Ritual', 'Concentration'].includes(header)) {
        spell[header] = value.toLowerCase() === 'true';
      } else {
        spell[header] = value;
      }
    });
    
    spells.push(spell as Spell);
  }
  
  return spells;
}

function parseCSVLine(line: string): string[] {
  const result = [];
  let current = '';
  let inQuotes = false;
  
  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    
    if (char === '"') {
      inQuotes = !inQuotes;
    } else if (char === ',' && !inQuotes) {
      result.push(current);
      current = '';
    } else {
      current += char;
    }
  }
  
  result.push(current); // Add the last field
  return result;
}

// Fallback data in case the CSV cannot be loaded
export const dummySpells: Spell[] = [
{
    Name: 'Chama Ígnea',
    Level: 1,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Cold',
    Description: 'This is the description for Spell 1.'
},
{
    Name: 'Raio Tempestuoso',
    Level: 2,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Lightning',
    Description: 'This is the description for Spell 2.'
},
{
    Name: 'Véu da Ilusão',
    Level: 3,
    School: 'Illusion',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Force',
    Description: 'This is the description for Spell 3.'
},
{
    Name: 'Toque Fúnebre',
    Level: 4,
    School: 'Necromancy',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Necrotic',
    Description: 'This is the description for Spell 4.'
},
{
    Name: 'Visão Profunda',
    Level: 5,
    School: 'Divination',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Radiant',
    Description: 'This is the description for Spell 5.'
},
{
    Name: 'Metamorfose Rápida',
    Level: 6,
    School: 'Transmutation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Psychic',
    Description: 'This is the description for Spell 6.'
},
{
    Name: 'Encanto Sutil',
    Level: 7,
    School: 'Enchantment',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Thunder',
    Description: 'This is the description for Spell 7.'
},
{
    Name: 'Explosão Solar',
    Level: 8,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Healing',
    Description: 'This is the description for Spell 8.'
},
{
    Name: 'Barreira Arcana',
    Level: 9,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Utility',
    Description: 'This is the description for Spell 9.'
},
{
    Name: 'Invocar Centelha',
    Level: 0,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Fire',
    Description: 'This is the description for Spell 10.'
},
{
    Name: 'Miragem Sombria',
    Level: 1,
    School: 'Illusion',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Cold',
    Description: 'This is the description for Spell 11.'
},
{
    Name: 'Corrente Espectral',
    Level: 2,
    School: 'Necromancy',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Lightning',
    Description: 'This is the description for Spell 12.'
},
{
    Name: 'Orbe da Verdade',
    Level: 3,
    School: 'Divination',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Force',
    Description: 'This is the description for Spell 13.'
},
{
    Name: 'Transmutar Pedra',
    Level: 4,
    School: 'Transmutation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Necrotic',
    Description: 'This is the description for Spell 14.'
},
{
    Name: 'Aura do Encantador',
    Level: 5,
    School: 'Enchantment',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Radiant',
    Description: 'This is the description for Spell 15.'
},
{
    Name: 'Chuva de Luz',
    Level: 6,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Psychic',
    Description: 'This is the description for Spell 16.'
},
{
    Name: 'Proteção Ancestral',
    Level: 7,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Thunder',
    Description: 'This is the description for Spell 17.'
},
{
    Name: 'Portal Etéreo',
    Level: 8,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Healing',
    Description: 'This is the description for Spell 18.'
},
{
    Name: 'Ilusão Perfeita',
    Level: 9,
    School: 'Illusion',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Utility',
    Description: 'This is the description for Spell 19.'
},
{
    Name: 'Sopro da Morte',
    Level: 0,
    School: 'Necromancy',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: true,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Fire',
    Description: 'This is the description for Spell 20.'
},
{
    Name: 'Olhar do Destino',
    Level: 1,
    School: 'Divination',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Cold',
    Description: 'This is the description for Spell 21.'
},
{
    Name: 'Forma Mutável',
    Level: 2,
    School: 'Transmutation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Lightning',
    Description: 'This is the description for Spell 22.'
},
{
    Name: 'Domínio Mental',
    Level: 3,
    School: 'Enchantment',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Force',
    Description: 'This is the description for Spell 23.'
},
{
    Name: 'Chama Curativa',
    Level: 4,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Necrotic',
    Description: 'This is the description for Spell 24.'
},
{
    Name: 'Escudo Temporal',
    Level: 5,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Radiant',
    Description: 'This is the description for Spell 25.'
},
{
    Name: 'Evocação Selvagem',
    Level: 6,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Psychic',
    Description: 'This is the description for Spell 26.'
},
{
    Name: 'Luz Fantasma',
    Level: 7,
    School: 'Illusion',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Thunder',
    Description: 'This is the description for Spell 27.'
},
{
    Name: 'Corrente Vital',
    Level: 8,
    School: 'Necromancy',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Healing',
    Description: 'This is the description for Spell 28.'
},
{
    Name: 'Olho Místico',
    Level: 9,
    School: 'Divination',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Utility',
    Description: 'This is the description for Spell 29.'
},
{
    Name: 'Transmutação Menor',
    Level: 0,
    School: 'Transmutation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Fire',
    Description: 'This is the description for Spell 30.'
},
{
    Name: 'Lâmina Mental',
    Level: 1,
    School: 'Enchantment',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Cold',
    Description: 'This is the description for Spell 31.'
},
{
    Name: 'Tempestade Prismática',
    Level: 2,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Lightning',
    Description: 'This is the description for Spell 32.'
},
{
    Name: 'Escudo do Guardião',
    Level: 3,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Force',
    Description: 'This is the description for Spell 33.'
},
{
    Name: 'Chama Espectral',
    Level: 4,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Necrotic',
    Description: 'This is the description for Spell 34.'
},
{
    Name: 'Ilusão do Eclipse',
    Level: 5,
    School: 'Illusion',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Radiant',
    Description: 'This is the description for Spell 35.'
},
{
    Name: 'Toque do Abismo',
    Level: 6,
    School: 'Necromancy',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Psychic',
    Description: 'This is the description for Spell 36.'
},
{
    Name: 'Olhar Profético',
    Level: 7,
    School: 'Divination',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Thunder',
    Description: 'This is the description for Spell 37.'
},
{
    Name: 'Forma Elemental',
    Level: 8,
    School: 'Transmutation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Healing',
    Description: 'This is the description for Spell 38.'
},
{
    Name: 'Vínculo Encantado',
    Level: 9,
    School: 'Enchantment',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Utility',
    Description: 'This is the description for Spell 39.'
},
{
    Name: 'Fulgor Ígneo',
    Level: 0,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: true,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Fire',
    Description: 'This is the description for Spell 40.'
},
{
    Name: 'Barreira Glacial',
    Level: 1,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Cold',
    Description: 'This is the description for Spell 41.'
},
{
    Name: 'Chuva de Meteoros',
    Level: 2,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Lightning',
    Description: 'This is the description for Spell 42.'
},
{
    Name: 'Reflexo Fantasmagórico',
    Level: 3,
    School: 'Illusion',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Force',
    Description: 'This is the description for Spell 43.'
},
{
    Name: 'Mão Esquelética',
    Level: 4,
    School: 'Necromancy',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Necrotic',
    Description: 'This is the description for Spell 44.'
},
{
    Name: 'Visão do Oráculo',
    Level: 5,
    School: 'Divination',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Radiant',
    Description: 'This is the description for Spell 45.'
},
{
    Name: 'Mutação Selvagem',
    Level: 6,
    School: 'Transmutation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Psychic',
    Description: 'This is the description for Spell 46.'
},
{
    Name: 'Aura Fascinante',
    Level: 7,
    School: 'Enchantment',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Thunder',
    Description: 'This is the description for Spell 47.'
},
{
    Name: 'Luz Purificadora',
    Level: 8,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Healing',
    Description: 'This is the description for Spell 48.'
},
{
    Name: 'Escudo Supremo',
    Level: 9,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Utility',
    Description: 'This is the description for Spell 49.'
},
{
    Name: 'Centelha Primordial',
    Level: 0,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Fire',
    Description: 'This is the description for Spell 50.'
},
{
    Name: 'Bruma Ilusória',
    Level: 1,
    School: 'Illusion',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Cold',
    Description: 'This is the description for Spell 51.'
},
{
    Name: 'Lamento das Sombras',
    Level: 2,
    School: 'Necromancy',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Lightning',
    Description: 'This is the description for Spell 52.'
},
{
    Name: 'Olho do Oráculo',
    Level: 3,
    School: 'Divination',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Force',
    Description: 'This is the description for Spell 53.'
},
{
    Name: 'Pele de Pedra',
    Level: 4,
    School: 'Transmutation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Necrotic',
    Description: 'This is the description for Spell 54.'
},
{
    Name: 'Aura do Hipnotista',
    Level: 5,
    School: 'Enchantment',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Radiant',
    Description: 'This is the description for Spell 55.'
},
{
    Name: 'Chama Selvagem',
    Level: 6,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Psychic',
    Description: 'This is the description for Spell 56.'
},
{
    Name: 'Barreira Protetora',
    Level: 7,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Thunder',
    Description: 'This is the description for Spell 57.'
},
{
    Name: 'Chuva de Espíritos',
    Level: 8,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Healing',
    Description: 'This is the description for Spell 58.'
},
{
    Name: 'Ilusão Suprema',
    Level: 9,
    School: 'Illusion',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Utility',
    Description: 'This is the description for Spell 59.'
},
{
    Name: 'Sopro Infernal',
    Level: 0,
    School: 'Necromancy',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: true,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Fire',
    Description: 'This is the description for Spell 60.'
},
{
    Name: 'Olhar Profundo',
    Level: 1,
    School: 'Divination',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Cold',
    Description: 'This is the description for Spell 61.'
},
{
    Name: 'Forma Etérea',
    Level: 2,
    School: 'Transmutation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Lightning',
    Description: 'This is the description for Spell 62.'
},
{
    Name: 'Domínio do Encantador',
    Level: 3,
    School: 'Enchantment',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Force',
    Description: 'This is the description for Spell 63.'
},
{
    Name: 'Chama do Caos',
    Level: 4,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Necrotic',
    Description: 'This is the description for Spell 64.'
},
{
    Name: 'Escudo do Tempo',
    Level: 5,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Radiant',
    Description: 'This is the description for Spell 65.'
},
{
    Name: 'Evocação Ancestral',
    Level: 6,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Psychic',
    Description: 'This is the description for Spell 66.'
},
{
    Name: 'Luz Ilusória',
    Level: 7,
    School: 'Illusion',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Thunder',
    Description: 'This is the description for Spell 67.'
},
{
    Name: 'Corrente Sombria',
    Level: 8,
    School: 'Necromancy',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Healing',
    Description: 'This is the description for Spell 68.'
},
{
    Name: 'Olho do Destino',
    Level: 9,
    School: 'Divination',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Utility',
    Description: 'This is the description for Spell 69.'
},
{
    Name: 'Transmutação Arcana',
    Level: 0,
    School: 'Transmutation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Fire',
    Description: 'This is the description for Spell 70.'
},
{
    Name: 'Encantamento Profundo',
    Level: 1,
    School: 'Enchantment',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Cold',
    Description: 'This is the description for Spell 71.'
},
{
    Name: 'Raio do Trovão',
    Level: 2,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Lightning',
    Description: 'This is the description for Spell 72.'
},
{
    Name: 'Manto Protetor',
    Level: 3,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Force',
    Description: 'This is the description for Spell 73.'
},
{
    Name: 'Chama Invocada',
    Level: 4,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Necrotic',
    Description: 'This is the description for Spell 74.'
},
{
    Name: 'Miragem Arcana',
    Level: 5,
    School: 'Illusion',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Radiant',
    Description: 'This is the description for Spell 75.'
},
{
    Name: 'Sussurro Fúnebre',
    Level: 6,
    School: 'Necromancy',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Psychic',
    Description: 'This is the description for Spell 76.'
},
{
    Name: 'Revelação Profunda',
    Level: 7,
    School: 'Divination',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Thunder',
    Description: 'This is the description for Spell 77.'
},
{
    Name: 'Forma Mutante',
    Level: 8,
    School: 'Transmutation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Healing',
    Description: 'This is the description for Spell 78.'
},
{
    Name: 'Aura Sublime',
    Level: 9,
    School: 'Enchantment',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Utility',
    Description: 'This is the description for Spell 79.'
},
{
    Name: 'Explosão Flamejante',
    Level: 0,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: true,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Fire',
    Description: 'This is the description for Spell 80.'
},
{
    Name: 'Barreira de Gelo',
    Level: 1,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Cold',
    Description: 'This is the description for Spell 81.'
},
{
    Name: 'Chama Fantasma',
    Level: 2,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Lightning',
    Description: 'This is the description for Spell 82.'
},
{
    Name: 'Ilusão Profunda',
    Level: 3,
    School: 'Illusion',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Force',
    Description: 'This is the description for Spell 83.'
},
{
    Name: 'Toque Sombrio',
    Level: 4,
    School: 'Necromancy',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Necrotic',
    Description: 'This is the description for Spell 84.'
},
{
    Name: 'Olhar Arcano',
    Level: 5,
    School: 'Divination',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Radiant',
    Description: 'This is the description for Spell 85.'
},
{
    Name: 'Transmutação Selvagem',
    Level: 6,
    School: 'Transmutation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Psychic',
    Description: 'This is the description for Spell 86.'
},
{
    Name: 'Encanto Hipnótico',
    Level: 7,
    School: 'Enchantment',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Thunder',
    Description: 'This is the description for Spell 87.'
},
{
    Name: 'Luz Restauradora',
    Level: 8,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Healing',
    Description: 'This is the description for Spell 88.'
},
{
    Name: 'Escudo Arcano',
    Level: 9,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Utility',
    Description: 'This is the description for Spell 89.'
},
{
    Name: 'Centelha Elemental',
    Level: 0,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Fire',
    Description: 'This is the description for Spell 90.'
},
{
    Name: 'Explosão Glacial',
    Level: 1,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Cold',
    Description: 'This is the description for Spell 91.'
},
{
    Name: 'Raio Congelante',
    Level: 2,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Lightning',
    Description: 'This is the description for Spell 92.'
},
{
    Name: 'Mestre das Sombras',
    Level: 3,
    School: 'Illusion',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Force',
    Description: 'This is the description for Spell 93.'
},
{
    Name: 'Toque Glacial',
    Level: 4,
    School: 'Necromancy',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Necrotic',
    Description: 'This is the description for Spell 94.'
},
{
    Name: 'Aura do Oráculo',
    Level: 5,
    School: 'Divination',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Radiant',
    Description: 'This is the description for Spell 95.'
},
{
    Name: 'Tempestade de Fogo',
    Level: 6,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Psychic',
    Description: 'This is the description for Spell 96.'
},
{
    Name: 'Corrente de Trovão',
    Level: 7,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Thunder',
    Description: 'This is the description for Spell 97.'
},
{
    Name: 'Portal Elemental',
    Level: 8,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Healing',
    Description: 'This is the description for Spell 98.'
},
{
    Name: 'Ilusão do Destino',
    Level: 9,
    School: 'Illusion',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Utility',
    Description: 'This is the description for Spell 99.'
},
{
    Name: 'Sopro do Inferno',
    Level: 0,
    School: 'Necromancy',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: true,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Fire',
    Description: 'This is the description for Spell 100.'
},
{
    Name: 'Olhar do Destino',
    Level: 1,
    School: 'Divination',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Cold',
    Description: 'This is the description for Spell 101.'
},
{
    Name: 'Raio do Trovão',
    Level: 2,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Lightning',
    Description: 'This is the description for Spell 102.'
},
{
    Name: 'Manto Protetor',
    Level: 3,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Force',
    Description: 'This is the description for Spell 103.'
},
{
    Name: 'Chama Invocada',
    Level: 4,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Necrotic',
    Description: 'This is the description for Spell 104.'
},
{
    Name: 'Miragem Arcana',
    Level: 5,
    School: 'Illusion',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Radiant',
    Description: 'This is the description for Spell 105.'
},
{
    Name: 'Sussurro Fúnebre',
    Level: 6,
    School: 'Necromancy',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Psychic',
    Description: 'This is the description for Spell 106.'
},
{
    Name: 'Revelação Profunda',
    Level: 7,
    School: 'Divination',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Thunder',
    Description: 'This is the description for Spell 107.'
},
{
    Name: 'Forma Mutante',
    Level: 8,
    School: 'Transmutation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Healing',
    Description: 'This is the description for Spell 108.'
},
{
    Name: 'Aura Sublime',
    Level: 9,
    School: 'Enchantment',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Utility',
    Description: 'This is the description for Spell 109.'
},
{
    Name: 'Explosão Flamejante',
    Level: 0,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: true,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Fire',
    Description: 'This is the description for Spell 110.'
},
{
    Name: 'Barreira de Gelo',
    Level: 1,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Cold',
    Description: 'This is the description for Spell 111.'
},
{
    Name: 'Chama Fantasma',
    Level: 2,
    School: 'Conjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Lightning',
    Description: 'This is the description for Spell 112.'
},
{
    Name: 'Ilusão Profunda',
    Level: 3,
    School: 'Illusion',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Force',
    Description: 'This is the description for Spell 113.'
},
{
    Name: 'Toque Sombrio',
    Level: 4,
    School: 'Necromancy',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '30 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'DEX Save',
    DamageEffect: 'Necrotic',
    Description: 'This is the description for Spell 114.'
},
{
    Name: 'Olhar Arcano',
    Level: 5,
    School: 'Divination',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '60 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'CON Save',
    DamageEffect: 'Radiant',
    Description: 'This is the description for Spell 115.'
},
{
    Name: 'Transmutação Selvagem',
    Level: 6,
    School: 'Transmutation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '90 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'WIS Save',
    DamageEffect: 'Psychic',
    Description: 'This is the description for Spell 116.'
},
{
    Name: 'Encanto Hipnótico',
    Level: 7,
    School: 'Enchantment',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '120 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'CHA Save',
    DamageEffect: 'Thunder',
    Description: 'This is the description for Spell 117.'
},
{
    Name: 'Luz Restauradora',
    Level: 8,
    School: 'Evocation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: true,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Healing',
    Description: 'This is the description for Spell 118.'
},
{
    Name: 'Escudo Arcano',
    Level: 9,
    School: 'Abjuration',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '180 ft',
    Verbal: true,
    Somatic: true,
    Ritual: false,
    Concentration: false,
    Attack: '',
    Save: 'STR Save',
    DamageEffect: 'Utility',
    Description: 'This is the description for Spell 119.'
},
{
    Name: 'Transmutação Arcana',
    Level: 0,
    School: 'Transmutation',
    CastingTime: '1 Action',
    Duration: 'Instantaneous',
    Range: '150 ft',
    Verbal: true,
    Somatic: true,
    Ritual: true,
    Concentration: false,
    Attack: '',
    Save: 'INT Save',
    DamageEffect: 'Fire',
    Description: 'This is the description for Spell 120.'
}
];
